mandelbrot:
	g++ -std=c++11 -O2 calc_mandelbrot_set_iterations.cpp -o calc_mandelbrot_set_iterations.o -I/home/doublepmcl/prefix/include -L/home/doublepmcl/prefix/lib
complex_num_text:
	g++ -std=c++11 -O2 complex_numbers_precision_test.cpp -o complex_numbers_precision_test.o -I/home/doublepmcl/prefix/include -L/home/doublepmcl/prefix/lib/libgmpxx
# g++ -std=c++11 -O2 complex_numbers_precision_test.cpp -o complex_numbers_precision_test.o -lgmp -L/home/doublepmcl/prefix/lib
